name: 18 - 3 - Reusable Workflows

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/18-1-reusable-workflows.yaml
    with:
      target-directory: test-dir
  e2e-tests:
    needs: deploy
    uses: MykytaKostiuk/github-actions-course-example-e2e/.github/workflows/e2e.yaml@main
    secrets: 
      # This token allows to read the code from the reusable workflow repo
      access-token: ${{ secrets.GH_TOKEN_RW_102 }}
